### ISSUE TITLE
Publish `fougas.msys2` to Open VSX

### ISSUE THREAD

**Issue by goyalyashpal** [okhlybov/vscode-msys2#1]
Hi!
I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [fougas.msys2]
Thanks!

[fougas.msys2]: https://open-vsx.org/vscode/item?itemName=fougas.msys2

**Comment by okhlybov** [comment]
I could do this if there is demand for it.

**Comment by goyalyashpal** [comment]
yes, many many ppl use VSCodium, and so, those have to go through many additional steps to set up the extension not available on open-vsx

**Comment by okhlybov** [comment]
> Hi! I just thought to ask that do u have any plans to publish ur extension on open-vsx?? See this for more details: [fougas.msys2](https://open-vsx.org/vscode/item?itemName=fougas.msys2) Thanks!

Done.
Please give it a try.

**Comment by goyalyashpal** [comment]
hi, thanks a lottttt for making it available and also the corresponding updates in the documentation/README (https://github.com/okhlybov/vscode-msys2/commit/68fb7c1e44110043e81d1df51cb7bd3888863636). thanks a lot 😇 

as for trying it, i dont have any experience with devt - i am just getting started. so, cant provide any other feedback yet 😅
